---
title: "Homework"
author: "Xuanheng HUANG"
header-includes:
   - \usepackage{dcolumn}
output: pdf_document
---

```{r setup, include=FALSE}
install_package_if_missing <- function(pkg) {
  if (! pkg %in% installed.packages()[, "Package"]) install.packages(pkg)
}

install_package_if_missing("pacman")

pacman::p_load(pacman,gmm,stargazer,rio,psych,tidyverse,lmtest,sandwich)

knitr::opts_chunk$set(echo=TRUE)

```

```{r, include=FALSE}
tinytex::install_tinytex()
```

## Table 1

```{r, echo = FALSE, results='asis', comment=NA}
# get the riskfree rate
FF4_monthlyKF <- import("Data/FF4_monthlyKF.csv")
FF4_monthlyKF <- FF4_monthlyKF[c("V1","V5")]
FF4_monthlyKF <- rename(FF4_monthlyKF,dt=V1,Rf=V5)
FF4_monthlyKF$dt <-as.character(FF4_monthlyKF$dt)
#annual risk free rate
FF4_monthlyKF$A_Rf <- FF4_monthlyKF$Rf*12  

T1_ptfs <- import("Data/Data_master.xlsx", sheet="T1_ptfs")
T1_ptfs$dt <-as.character(T1_ptfs$dt)

# change date format in the dt
T1_ptfs$dt <-substr(T1_ptfs$dt,1,nchar(T1_ptfs$dt)-2) 

# Add risk free rate to the table
T1_ptfs <- merge(T1_ptfs, FF4_monthlyKF, by="dt")  

col = c("LeadR","MidR","LagR","Lead","Mid","Lag","LL","LLStrong")

#get annual percent of returns
for (i in col){               
  T1_ptfs[,i] <- T1_ptfs[,i]*100*12
}

#excess returns
col = c("Lead","Mid","Lag")
for (i in col){               
  Addex <- paste("ex_",i,sep="")
  T1_ptfs[,Addex] <- T1_ptfs[,i] - T1_ptfs$A_Rf
}

#first row
T1_reg1 <- lapply(c("LeadR","MidR","LagR","LL","LLStrong"), function (x) lm(T1_ptfs[,x] ~ 1))
T1_reg1 <- lapply(T1_reg1, coeftest, vcov = NeweyWest, lag = 24)


#second row
T1_reg2 <- lapply(c("ex_Lead","ex_Mid","ex_Lag","LL","LLStrong"), function (x) lm(T1_ptfs[,x] ~ mktrf, data=T1_ptfs))
T1_reg2 <- lapply(T1_reg2, coeftest, vcov = NeweyWest, lag = 24)


# third row
T1_reg3 <- lapply(c("ex_Lead","ex_Mid","ex_Lag","LL","LLStrong"), function (x) lm(T1_ptfs[,x] ~ mktrf + smb + hml, data=T1_ptfs))
T1_reg3 <- lapply(T1_reg3, coeftest, vcov = NeweyWest, lag = 24)



# output table 1
tab1 <- T1_reg3

for (i in 1:5){
  tab1[[i]][1,] <- T1_reg1[[i]][1,]
}

for (i in 1:5){
  tab1[[i]][2,] <- T1_reg2[[i]][1,]
}

for (i in 1:5){
  tab1[[i]][3,] <- T1_reg3[[i]][1,]
}

table_1<-stargazer(tab1,
          title="Lead-Lag Portfolio Sorting (Max Correlation)",
          intercept.bottom=FALSE,
          omit = 4,
          align=TRUE,
          header = FALSE,
          column.labels = c('Lead', 'Mid', 'Lag', 'LL', 'LLStrong'),
          covariate.labels=c("Average return","CAPM $\\alpha$","FF3 $\\alpha$"),
          no.space=TRUE,
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          style="aer")

```

## Table 3
```{r, echo = FALSE, results='asis', comment=NA}
## Table 3 
T3_ptfs <- import("Data/Data_master.xlsx", sheet="T3_ptfs")
T3_ptfs$dt <-as.character(T3_ptfs$dt)

# change date format in the dt
T3_ptfs$dt <-substr(T3_ptfs$dt,1,nchar(T3_ptfs$dt)-2) 

# merge with table 1
T3_ptfs <- merge(T3_ptfs, T1_ptfs, by="dt")  

col = c("LL38","LLStrong38","LL49","LLStrong49")

#get annual percent of returns
for (i in col){               
  T3_ptfs[,i] <- T3_ptfs[,i]*100*12
}

# first row
T3_reg1 <- lapply(col, function (x) lm(T3_ptfs[,x] ~ 1))
T3_reg1 <- lapply(T3_reg1, coeftest, vcov = NeweyWest, lag = 12)

# second row
T3_reg2 <- lapply(col, function (x) lm(T3_ptfs[,x] ~ mktrf, data=T3_ptfs))
T3_reg2 <- lapply(T3_reg2, coeftest, vcov = NeweyWest, lag = 12)

# third row
T3_reg3 <- lapply(col, function (x) lm(T3_ptfs[,x] ~ mktrf + smb + hml, data=T3_ptfs))
T3_reg3 <- lapply(T3_reg3, coeftest, vcov = NeweyWest, lag = 12)


# output table 3
tab2 <- T3_reg3

for (i in 1:4){
  tab2[[i]][1,] <- T3_reg1[[i]][1,]
}

for (i in 1:4){
  tab2[[i]][2,] <- T3_reg2[[i]][1,]
}

for (i in 1:4){
  tab2[[i]][3,] <- T3_reg3[[i]][1,]
}

stargazer(tab2,
          title="Lead-Lag Portfolio Sorting - 38 and 49 Industries",
          intercept.bottom=FALSE,
          omit = 4,
          align=TRUE,
          header = FALSE,
          column.labels = c('Lead', 'Mid', 'Lag', 'LL', 'LLStrong'),
          covariate.labels=c("Average return","CAPM $\\alpha$","FF3 $\\alpha$"),
          no.space=TRUE,
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          style="aer")

```

\newpage

## Table 7

```{r, echo = FALSE, warning=FALSE, message=FALSE}
## Table 7
T7_factors <- import("Data/Data_master.xlsx", sheet="T7_factors", which=col)
col = c("dt","LLStrong30", "mktrf", "smb", "hml", "rmw", "cma", "q_mkt", "q_me", "q_ia", "q_roe", "L", "M", "N", "mom")
colnames(T7_factors) <- col
T7_factors$dt <-as.character(T7_factors$dt)
# change date format in the dt
T7_factors$dt <-substr(T7_factors$dt,1,nchar(T7_factors$dt)-2) 

col = c("LLStrong30", "mktrf", "smb", "hml", "rmw", "cma", "q_mkt", "q_me", "q_ia", "q_roe", "L", "M", "N", "mom")

#get annual percent of returns
for (i in col){               
  T7_factors[,i] <- T7_factors[,i]*100*12
}

# first column
T7_reg1 <- lm(LLStrong30 ~ mktrf+smb+hml+rmw+cma, data = T7_factors)
T7_reg1 <- coeftest(T7_reg1, vcov. = NeweyWest, lag = 12)
T7_reg1[,4] <- pnorm(q=T7_reg1[,3], lower.tail=FALSE)

# second column
T7_reg2 <- lm(LLStrong30 ~ q_mkt+q_me+q_ia+q_roe, data = T7_factors)
T7_reg2 <- coeftest(T7_reg2, vcov. = NeweyWest, lag = 12)
# T7_reg2[,4] <- pnorm(q=T7_reg2[,3], lower.tail=FALSE)

# third column
T7_reg3 <- lm(LLStrong30 ~ mom, data = T7_factors)
T7_reg3 <- coeftest(T7_reg3, vcov. = NeweyWest, lag = 12)
# T7_reg3[,4] <- pnorm(q=T7_reg3[,3], lower.tail=FALSE)

# forth column
T7_reg4 <- lm(LLStrong30 ~ L+mom, data = T7_factors)
T7_reg4 <- coeftest(T7_reg4, vcov. = NeweyWest, lag = 12)
# T7_reg4[,4] <- pnorm(q=T7_reg4[,3], lower.tail=FALSE)

# fifth column
T7_reg5 <- lm(LLStrong30 ~ L+M+N+mom, data = T7_factors)
T7_reg5 <- coeftest(T7_reg5, vcov. = NeweyWest, lag = 12)
# T7_reg5[,4] <- pnorm(q=T7_reg5[,3], lower.tail=FALSE)

p_reg1 <- pnorm(q=T7_reg1[,3], lower.tail=FALSE)
p_reg2 <- pnorm(q=T7_reg2[,3], lower.tail=FALSE)
p_reg3 <- pnorm(q=T7_reg3[,3], lower.tail=FALSE)
p_reg4 <- pnorm(q=T7_reg4[,3], lower.tail=FALSE)
p_reg5 <- pnorm(q=T7_reg5[,3], lower.tail=FALSE)
```

```{r, echo = FALSE, results='asis'}
# output table 7
stargazer(list(T7_reg1,T7_reg2,T7_reg3,T7_reg4,T7_reg5),
          p=list(p_reg1,p_reg2,p_reg3,p_reg4,p_reg5),
          title="The Disconnect between LL and Other Factors (II)",
          align=TRUE,
          header = FALSE,
          column.labels = c('FF5', 'HXZ q-factors', 'Carhart MOM 1', 'Carhart MOM 2', 'Carhart MOM 3'),
          keep= "Constant",
          covariate.labels=c("$\\alpha_{LL}$"),
          no.space=TRUE,
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          style="aer")
```

## Table 9

```{r, echo = FALSE, results='asis', comment=NA}
## Table 9

# Import factors
T1_factors <- import("Data/Data_master.xlsx", sheet="T1_factors")
T1_factors$LL<-T1_factors$LL*100
T1_factors$dt <-as.character(T1_factors$dt)
T1_factors$dt <-substr(T1_factors$dt,1,nchar(T1_factors$dt)-2) 

# Add risk free rate and delete useless columns
T1_factors <- merge(T1_factors, FF4_monthlyKF, by="dt") 
col = c("LeadReal","MidReal","LagReal","Lead","Mid","Lag","LLStrong","A_Rf")
T1_factors[,col] <- list(NULL)

import_portfolios = function(file){
  tablename <- import(file)
  tablename <- rename(tablename,dt=V1)
  #tablename <- subset(tablename, dt > 197200 & dt < 201300)
  tablename$dt <-as.character(tablename$dt)
  tablename <- merge(T1_factors, tablename, by="dt") 
  
  #excess returns
  for (i in 7:ncol(tablename)){               
    tablename[,i] <- tablename[,i] - tablename$Rf
  }
  
  return(tablename)
}

ind30 <- import_portfolios("Data/30_industry_pfs.csv")
ind38 <- import_portfolios("Data/38_industry_pfs.csv")
ind49 <- import_portfolios("Data/49_industry_pfs.csv")
booksize <- import_portfolios("Data/25_book_size_all.csv")

# moment function
g = function(theta, dat){
  dat[is.nan(dat)] <- 0
  b = theta
  r_ex = dat[,c(6:ncol(dat),1)]
  X = dat[,c(2,3,4,1)]
  r_ex * kronecker((rep(1, nrow (X)) - X %*% b), t(rep(1, ncol(r_ex) )))
}

# 1-step gmm estimator
fit_gmm1 = gmm(g, as.matrix(ind30[,-1]), rep(0, 4), weightsMatrix = diag(31),
               vcov = 'HAC')
fit_gmm2 = gmm(g, as.matrix(ind38[,-1]), rep(0, 4), weightsMatrix = diag(39),
               vcov = 'HAC')
fit_gmm3 = gmm(g, as.matrix(ind49[,-1]), rep(0, 4), weightsMatrix = diag(50),
               vcov = 'HAC')
fit_gmm4 = gmm(g, as.matrix(booksize[,-1]), rep(0, 4), weightsMatrix = diag(26),
               vcov = 'HAC')

varF = cov(T1_factors[,c("mktrf","smb","hml","LL")])

compute_lambda <- function(fitgmm){
  lambda_coef = as.numeric(varF %*% fitgmm$coefficients)
  v_lambda = varF %*% vcov(fitgmm) %*% t(varF)
  se_lambda = as.numeric(diag(v_lambda)^.5)
  t_lambda = lambda_coef/se_lambda
  p_lambda = 2*pnorm(q=abs(t_lambda), lower.tail=FALSE)
  lambda <- list("coef"=lambda_coef,"se"=se_lambda,"t"=t_lambda, "p"=p_lambda)
  return(lambda)
}

lambda_gmm1 <- compute_lambda(fit_gmm1)
lambda_gmm2 <- compute_lambda(fit_gmm2)
lambda_gmm3 <- compute_lambda(fit_gmm3)
lambda_gmm4 <- compute_lambda(fit_gmm4)
#lambda_rows <- c("$\\lambda_{MKT}$","","$\\lambda_{SMB}$","","$\\lambda_{HML}$","","$\\lambda_{LL}$")

stargazer(list(fit_gmm1,fit_gmm2,fit_gmm3,fit_gmm4),
          out = "XuanhengHuang_Homework.tex",
          coef = list(lambda_gmm1$coef,lambda_gmm2$coef,lambda_gmm3$coef,lambda_gmm4$coef),
          se = list(lambda_gmm1$se,lambda_gmm2$se,lambda_gmm3$se,lambda_gmm4$se),
          t = list(lambda_gmm1$t,lambda_gmm2$t,lambda_gmm3$t,lambda_gmm4$t),
          p = list(lambda_gmm1$p,lambda_gmm2$p,lambda_gmm3$p,lambda_gmm4$p),
          title="Price of Risk",
          align=TRUE,
          header = FALSE,
          column.labels = c('30 industries', '38 industries', '49 industries', 'BE/ME and Size (25)'),
          covariate.labels=c("$\\lambda_{MKT}$","$\\lambda_{SMB}$","$\\lambda_{HML}$","$\\lambda_{LL}$"),
          no.space=TRUE,
          omit.stat = "all",
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          style="aer")

stargazer(list(fit_gmm1,fit_gmm2,fit_gmm3,fit_gmm4),
          out = "XuanhengHuang_Homework.tex",
          title="Pricing Kernel Loading",
          align=TRUE,
          header = FALSE,
          column.labels = c('30 industries', '38 industries', '49 industries', 'BE/ME and Size (25)'),
          covariate.labels=c("$b_{MKT}$","$b_{SMB}$","$b_{HML}$","$b_{LL}$"),
          no.space=TRUE,
          omit.stat = "all",
          model.numbers = FALSE,
          dep.var.labels.include = FALSE,
          style="aer")
```